### ISSUE TITLE
CreateTicketAsEndUser

### ISSUE THREAD

**Issue by jozigold** [eneifert/ZenDeskApi#1]
Hi, I am creating a ticket using the CreateTicketAsEndUser. I am setting

t.TicketTypeId = (int)TicketType.Problem;
t.PriorityId = (int) TicketPriorities.Urgent;
In Zend it is not showing the ticket created with these settings. 

Thanks

**Comment by eneifert** [comment]
Hello,

When you assume the identity of an end user I don't think you can set those properties. Try to create the ticket using the CreatTicket method and set the RequesterName and RequesterEmail or RequesterId along with anything else you want to set. 

Let me know if that helps.
Eric
