### ISSUE TITLE
How do I do Attachments?

### ISSUE THREAD

**Issue by HorseFly** [eneifert/ZenDeskApi#2]
Hi,

I am using your Zendesk API Wrapper (Thanks for sharing this!) to import our bugs from 16Bugs.com to ZenDesk.  So far I have everything working, except I can't figure out the attachments.  First off, I have attachments on the bug itself  and the comments in 16Bugs but in ZenDesk it seems like it only allows attachments to comments.  Is that right?

For each comment, I am adding attachments if they exist:

//create ticket
...
int ZenID = _api.CreateTicket(ticket);
...

DataRow[] comments = GetComments(bugid);  //gets 16Bugs comments for bugid
foreach (DataRow cmt in comments)
{
       ZenDeskApi.Model.Comment comment = new ZenDeskApi.Model.Comment();
       comment.Value = cmt["Text"].ToString();
       comment.IsPublic = true;
       comment.AuthorId = ZUSER_BTS;                                

```
   //Comment Attachments
   string cid = cmt["ID"].ToString();
   DataRow[] cups = GetAttachments(cid); //gets 16Bugs comment attachments
   foreach (DataRow cup in cups)
    {
      ZenDeskApi.Model.Attachment catt = new ZenDeskApi.Model.Attachment();
      catt.ContentType = cup["Content"].ToString();
      catt.FileName = cup["Original_Name"].ToString();
      catt.Size = Convert.ToInt32(cup["Size"].ToString());
      catt.Url = cup["Url"].ToString();
      comment.Attachments.Add(catt);
    }
    _api.AddComment(ZenID, comment);
```

 }

This creates my comment, but with no attachments.  Could it be the ContentType?  These are the ones I have from 16Bugs:

application/msword
application/pdf
application/vnd.ms-excel
application/vnd.ms-project
application/vnd.openxmlformats-officedocument.word
application/zip
binary/octet-stream
image/gif
image/jpeg
image/png
image/tiff
image/x-bmp

Any help is greatly appreciated!

**Comment by eneifert** [comment]
Hello,

I have now added the ability to do attachments. One thing to note though is they don't quite work like you would expect. Here is some sample code as to how to do attachments:

void UploadAttachment()
        {
            var token = _api.UploadAttachment(new ZenFile()
                                               {
                                                   FileName = "sample_file.png",
                                                   ContentType = "image/png",
                                                   FileData = File.ReadAllBytes("sample_file.png")
                                               });

```
        int id = _api.CreateTicket(new Ticket()
                                       {
                                           Description = "test",
                                           RequesterId = requesterId,
                                           PriorityId = (int) TicketPriorities.Normal,
                                           Subject = "test",
                                           AttachmentsToken = token
                                       });

        }
```

*Note: If you want to do multiple attachments use the method "UploadAttachments";

Hope this helps!
Eric

**Comment by HorseFly** [comment]
Oh wow!  Thanks a lot for adding this.  

Is there anyway to add the attachments per comment or do I have to put them all on the ticket?  I think we can deal with them all being on the ticket, but coming from 16Bugs, we have both situations.  I think ZenDesk allows that as well, but I didn't check the API documentation to see if is possible from that end.

Thanks again!

**Comment by eneifert** [comment]
Glad I could help.

To add an attachment to a comment just set the Comment.AttachmentsToken instead.

Let me know if you have any other questions,
Eric
