### ISSUE TITLE
Weak reference

### ISSUE THREAD

**Issue by Mikhail-Zakharov** [eneifert/ZenDeskApi#3]
ZenDeskApi project contains RestSharp.dll. 

RestSharp.dll is referenced to Newton.Json.Net35.dll

Need to add correct assembly from http://json.codeplex.com/releases/view/58535 or change references in RestSharp.dll if it's possible.

Fusion Log:

**\* Assembly Binder Log Entry  (20.05.2011 @ 12:41:27) ***

The operation failed.
Bind result: hr = 0x80070002. The system cannot find the file specified.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\AREA\DEVELOP\ZendeskSLAConnector\ZendDeskApi\ZExplorer\bin\Debug\ZExplorer.vshost.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: User = DOMAIN\user
LOG: DisplayName = Newtonsoft.Json.Net35, Version=4.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
 (Fully-specified)
LOG: Appbase = file:///C:/AREA/DEVELOP/ZendeskSLAConnector/ZendDeskApi/ZExplorer/bin/Debug/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = ZExplorer.vshost.exe
Calling assembly : RestSharp, Version=100.0.0.0, Culture=neutral, PublicKeyToken=null.

LOG: Start binding of native image Newtonsoft.Json.Net35, Version=4.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed.
WRN: No matching native image found.
LOG: IL assembly loaded from C:\AREA\DEVELOP\ZendeskSLAConnector\ZendDeskApi\ZExplorer\bin\Debug\Newtonsoft.Json.Net35.dll.

**Comment by eneifert** [comment]
Hmm, I must say I am somewhat confused, I tried using the GetOgranizations method without the reference and it worked fine for me. But I went ahead and added the reference anyways. Re-open this thread if it is still a problem.

Best of luck,
