### ISSUE TITLE
Problem uploading attachments

### ISSUE THREAD

**Issue by bwgabel** [eneifert/ZenDeskApi#4]
I am trying to upload an attachemnt named Test1234.txt.  The api acts like it was successful, however when I open the uploaded file from the ZenDesk ticket it always reads as follows:

filename=Test1234.txt&data-binary=System.Byte%5b%5d

Thanks,
Brandon

*********************\* My Code*********************************

```
    System.Collections.Generic.List<ZenFile> zFileList = new System.Collections.Generic.List<ZenFile>();


    protected void Page_Load(object sender, EventArgs e)
    {

        if (!IsPostBack)
        {
            Session["zFileList"] = null;
        }
        else if (Session["zFileList"] != null)
        {
            zFileList = (System.Collections.Generic.List<ZenFile>)Session["zFileList"];
        }
   }

   protected void btnSubmit_Click(object sender, EventArgs e)
   {
        ZenDeskApi.ZenDeskApi _api = new ZenDeskApi.ZenDeskApi(Site, Email, Password);
        Ticket zdTicket = new Ticket();
        zdTicket.RequesterEmail = "fake@email.com";
        zdTicket.Subject = this.txtSubject.Text;
        zdTicket.Description = this.txtContent.Text;
        zdTicket.RequesterName = "Joe Blow";
        zdTicket.ViaId = (int)TicketViaType.WebServiceOrApi;
        zdTicket.TicketTypeId = (int)TicketType.Question;
        if (zFileList != null)
        {
            zdTicket.AttachmentsToken = _api.UploadAttachments(zFileList);
        }

        int ticketID = _api.CreateTicket(zdTicket);

        zdTicket = _api.GetTicketById(ticketID);
   }

   protected void ProcessUpload(object sender, AjaxControlToolkit.AsyncFileUploadEventArgs e) 
    {
        ZenDeskApi.ZenDeskApi _api = new ZenDeskApi.ZenDeskApi(Site, Email, Password);

        ZenFile zFile = new ZenFile();
        zFile.FileName = AsyncFileUpload1.FileName;
        zFile.ContentType = AsyncFileUpload1.ContentType;
        zFile.FileData = AsyncFileUpload1.FileBytes;

        zFileList.Add(zFile);

        Session["zFileList"] = zFileList;

    }
```

*********************\* My Code*********************************

I have tested the ZenFile and confirmed that I can convert the FileData back to a text file and it looked right.  What am I doing wrong??

**Comment by eneifert** [comment]
Hello Brandon,

Could you tell me what the zFile.ContentType is set to? Is it "text/plain"? Here is a list of common content types: http://webdesign.about.com/od/multimedia/a/mime-types-by-content-type.htm

**Comment by bwgabel** [comment]
Yes the ContentType is set to "text/plain".  I also uploaded a jpg file "Koala2.jpg".  The content type on that upload was "image/jpeg" and the results were the same as the text files.  The jpg as it was downloaded from the zendesk ticket is attached.

Thanks,
Brandon Gabel

-----Original Message-----

**Comment by eneifert** [comment]
Brandon,

I was able to see your problem and I re-wrote the UploadAttachment method so this is now fixed. Although I never could find out exactly what the problem was, I know it had something to do with RestSharp and ZenDesk not playing nice together. I may submit something to the RestSharp team.

If you get the latest now you should be good to go. 

Let me know if you have any other questions,
Eric

**Comment by bwgabel** [comment]
Works great.  Thanks Eric.

-----Original Message-----
