### ISSUE TITLE
Testing ZenDeskApi

### ISSUE THREAD

**Issue by minals** [eneifert/ZenDeskApi#5]
I have created another visual studio test project to use the functionality of ZenDeskApi. I have added a reference to ZenDeskApi in the test project. When I try to create a new instance of ZenDeskApi, I get an error as ZenDeskApi is looking for some specific location for RestClient ( in the core.cs). My restclient is stored in a different location. Where do I change the location?

I have created a test project as I want to step through the code.

**Comment by eneifert** [comment]
Could you please post the complete error and your code.

Thanks,
Eric

**Comment by minals** [comment]
Sure.
I have added another project called ZenDesk and have added a reference to ZenDeskApi.

## In the form load event of the default.aspx.vb page..here is the code

Imports ZenDeskApi

Public Class _Default
    Inherits System.Web.UI.Page

```
Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load

    Dim _api As ZenDeskApi.ZenDeskApi = New ZenDeskApi.ZenDeskApi("my url", "email", "password")

End Sub
```

## End Class

Here is the error, I am getting..

No source Available
There is no source code available for the current location.
Source file information:
RestSharp.DLL!RestSharp.RestClient.RestClient(string baseUrl) Line 67

Source file information:

Locating source for 'C:\Users\ericn\Documents\Visual Studio 2010\Projects\RestSharp\RestSharp\RestClient.cs".
Checksum: MD5{34 2e 78 36 6f 7c d4 53 4e 29 8c 5a 77 90 c6 39}
The file 'C:\Users\ericn\Documents\Visual Studio 2010\Proejcts\RestSharp\RestSharp\RestClient.cs' does not exist.
Looking in a script documents for 'C:\Users\ericn\Documents\Visual Studio 2010\Projects\RestSharp\RestSharp\RestClient.cs'
The file was not found in a project.

**Comment by eneifert** [comment]
The broken reference should be fixed now. Let me know if it is not.

**Comment by minals** [comment]
Thanks for the update. I downloaded the new version with the fix but unable to find RestClient.cs file or RestSharp folder in any of the existing directories. When I step thru the code, a window pops up to provide correct path for RestClient.cs file. It is showing me the old path :

'C:\Users\ericn\Documents\Visual Studio 2010\Projects\RestSharp\RestSharp\RestClient.cs".

I am not able to find the directory where RestClient.cs exists.

Thanks for your help.

**Comment by minals** [comment]
Thanks for the update. I downloaded the new version with the fix but unable to find RestClient.cs file or RestSharp folder in any of the existing directories. When I step thru the code, a window pops up to provide correct path for RestClient.cs file. It is showing me the old path :

'C:\Users\ericn\Documents\Visual Studio 2010\Projects\RestSharp\RestSharp\RestClient.cs".

I am not able to find the directory where RestClient.cs exists.

Thanks for your help. 

-----Original Message-----

**Comment by eneifert** [comment]
Hmm, I cannot see where this old reference could be. I can not seem to reproduce your problem. However I have now added this project to Nuget. So if you are using Visual Studio you can set this up by right clicking on "References" (under your project) then click on "Add Library Package Reference". Search for "Zendesk" in the "Online" section and then click on install.

Let me know if this fixes it.

**Comment by minals** [comment]
Hi,

I have used Zendesk api calls to create a new ticket into the corresponding zendesk account. For some reason, I am not able to create a ticket with another organization other than the requestor's organization. Is there a way to create a ticket with the other organization id other than the requestor's organization id? I have included organization id into the request.

How do you make the comment private? I have tried updating ticket with comment set to <is-public> to false but does not seem to be working.

As you have created a whole application using zendesk API, you have better experience than I do so I thought of writing you my questions.

Thanks,

Minal

-----Original Message-----
