### ISSUE TITLE
Group.Users does not get populated after fetching Group(s)

### ISSUE THREAD

**Issue by ikalatch** [eneifert/ZenDeskApi#7]
Group.Users and Group.UserIds do not get populated after fetching Group(s) through either GetGroup(groupId) ot GetGroups().
Maybe the Users property should not be in the Group class at all to avoid confusion and instead add a new method GetUsersForGroup(groupId)? I see that the UserIds property is used for the creation and the updates of Groups, though.

**Comment by eneifert** [comment]
Thanks for the suggestion. But yeah, so far zendesk is not consistent as far as what fields get returned from what api calls so I think I am going to leave it as is for now.
