### ISSUE TITLE
Organization.Users contains Null

### ISSUE THREAD

**Issue by Mikhail-Zakharov** [eneifert/ZenDeskApi#9]
Use ZenDeskApi 1.01 via Nuget

Description:

Try to get an users from defined organization. 

(Opganization) oOrg = ZenDeskApi.GetOgranizationById(sOrganizationID);  //it's ok.

But oOrg.Users contains null  (On a ZenDesk portal this organization has an users). Catched server response (via Fiddler):

<?xml version="1.0" encoding="UTF-8"?>
<organization>
  <created-at type="datetime">2011-05-23T17:56:22+04:00</created-at>
  <default></default>
  <details></details>
  <group-id type="integer" nil="true"></group-id>
  <id type="integer">20159201</id>
  <is-shared type="boolean">true</is-shared>
  <is-shared-comments type="boolean">true</is-shared-comments>
  <name>TESTORG</name>
  <notes></notes>
  <suspended type="boolean">false</suspended>
  <updated-at type="datetime">2011-07-25T11:21:02+04:00</updated-at>
  <current-tags>customer</current-tags>
</organization>

Other strange thing (maybe referenced with one). Method ZenDeskApi.GetUsers returns not of all users.

**Comment by Mikhail-Zakharov** [comment]
I found that ZenDeskApi.GetUsers returns only 15 records. It meets manual:
"Returns a collection of users that has a name matching the query passed in through the URL. The list is paginated using offsets. If 15 elements are returned (the page limit), use ?page=2 to check for the next 15 and so on."

ZenDeskApi.GetUsers does not contain any paging parameters.

UPDATE.

I fixed it this way.

```
    public List<User> GetUsers()
    {
        //return GetCollection<User>(Users);
        List<User> result;
        result=(GetCollection<User>(Users));
        List<User> tmpresult;
        int counter = 2;
        string paging=".xml?page={0}";

        tmpresult=(GetCollection<User>(Users+string.Format(paging, counter)));
        while (tmpresult.Count != 0)
        {
            result.AddRange (tmpresult);
            counter += 1;
            tmpresult = (GetCollection<User>(Users + string.Format(paging, counter)));
        }
        return result; 
    }
```

**Comment by Mikhail-Zakharov** [comment]
When i call ZenDeskApi.GetOgranizationById(sOrganizationID) client send only single request
GET /organizations/20133245.xml

But there is no request
GET /organizations/#{id}/users.xml

UPDATE.

I fixed it this way:

```
     public Organization GetOgranizationById(int id)
    {
        var request = new ZenRestRequest
        {
            Method = Method.GET,
            Resource = string.Format("{0}/{1}.xml", _organizations, id)
        };

        Organization tmpresult;
        tmpresult = Execute<Organization>(request);

        List<User> tmpresultU;
        tmpresultU = GetCollection<User>(string.Format("{0}/{1}/users.xml", _organizations, id));

        tmpresult.Users = tmpresultU;
        //return Execute<Organization>(request);   
        return tmpresult;
    }  
```

**Comment by eneifert** [comment]
Hey guys,

I no longer have a testing environment that I can use to keep supporting this api. Is anyone else out there willing to take this project over? Let me know and I will post in the zendesk forum to send all future requests to you.

Thanks,
Eric
